Repository ToKyun02/Taskify, pull requests merged in 2025-02, with the labels that each got.

#14 Feat/10/auth component
  package-lock.json
  package.json
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/_components/LoginForm.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/_components/Checkbox.tsx
  src/app/(auth)/signup/_components/SignupForm.tsx
  src/app/(auth)/signup/page.tsx
  src/components/auth/Field.tsx
  src/components/auth/SubmitButton.tsx
  src/constants/auth.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#16 Feat/12/sidebar component
  src/app/mydashboard/layout.tsx
  src/app/mydashboard/page.tsx
  src/assets/images/sidebar_logo.png
  src/components/Sidebar/ArrowLeft.tsx
  src/components/Sidebar/ArrowRight.tsx
  src/components/Sidebar/Dot.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarItemList.tsx
  src/components/Sidebar/SidebarLogo.tsx
  src/components/Sidebar/SidebarPaginationControls.tsx
  src/utils/chunkArray.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#22 Refactor/19/codereveiw chanki
  src/app/(public)/_components/Footer.tsx
  src/app/(public)/_components/Header.tsx
  src/app/(public)/_components/Nav.tsx
  src/app/(public)/_components/type.tsx
  src/app/(public)/landing/_components/Feature.tsx
  src/app/(public)/privacy/_components/Typography.tsx
  src/app/(public)/privacy/page.tsx
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#26 Feat/21/button
  package-lock.json
  package.json
  src/components/ui/Button/Button.tsx
  src/utils/helper.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#36 Feat/23/pagination button component
  src/components/Sidebar/ArrowLeft.tsx
  src/components/Sidebar/ArrowRight.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarPaginationControls.tsx
  src/components/pagination/Arrow.tsx
  src/components/pagination/PaginationControls.tsx
  src/constants/paths.ts
  src/hooks/useChunkPagination.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#37 Feat/27/profile
  next.config.ts
  src/components/ui/Avatar/Avatar.tsx
  src/components/ui/Avatar/StackAvatars.tsx
  src/constants/colors.ts
  src/utils/helper.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#35 Feat/11/signup page
  src/apis/users/index.ts
  src/apis/users/types.ts
  src/app/(auth)/_components/Header.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/_components/LoginForm.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/_components/SignupForm.tsx
  src/app/(auth)/signup/page.tsx
  src/components/auth/SubmitButton.tsx
  src/utils/network/axiosHelper.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#62 Feat/28/chip
  src/assets/icons/check.svg
  src/components/ui/Chip/ColorChip.tsx
  src/components/ui/Chip/ColorPicker.tsx
  src/components/ui/Chip/NumberChip.tsx
  src/components/ui/Chip/RoundChip.tsx
  src/components/ui/Chip/TagChip.tsx
  src/constants/colors.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#63 Feat/24/mydashboardcard component
  src/apis/dashboards/mockData.ts
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarItemList.tsx
  src/components/mydashboard-card/MyDashboardCard.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#70 Refactor/69/landing folder structure
  src/app/(public)/_components/Header.tsx
  src/app/(public)/_components/Logo.tsx
  src/app/(public)/_components/Nav.tsx
  src/app/(public)/faq/page.tsx
  src/app/(public)/landing/page.tsx
  src/app/(public)/layout.tsx
  src/app/(public)/page.tsx
  src/app/(public)/privacy/page.tsx
  src/app/page.tsx
  src/components/landing/Accordion.tsx
  src/components/landing/Feature.tsx
  src/components/landing/Hero.tsx
  src/components/landing/Setting.tsx
  src/components/landing/SmoothScroll.tsx
  src/components/landing/layout/Footer.tsx
  src/components/landing/layout/Header.tsx
  src/components/landing/layout/Inner.tsx
  src/components/landing/layout/Main.tsx
  src/components/landing/layout/SubHeader.tsx
  src/components/landing/layout/type.tsx
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#68 Feat/38/dashboard layout
  src/app/(dashboard)/dashboard/page.tsx
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/mydashboard/page.tsx
  src/app/mydashboard/layout.tsx
  src/app/mydashboard/page.tsx
  src/components/Sidebar/Sidebar.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#71 Feat/32/login page
  src/apis/auth/index.ts
  src/apis/auth/types.ts
  src/apis/users/index.ts
  src/apis/users/types.ts
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/components/auth/Checkbox.tsx
  src/components/auth/Header.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/hooks/useAuthStore.tsx
  src/stores/authStore.ts
  src/utils/network/axiosHelper.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#73 Feat/30/dropdown
  src/assets/icons/check_gray.svg
  src/components/ui/Dropdown/Dropdown.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#74 Feat/61/api-dashboard
  src/apis/dashboards/index.ts
  src/apis/dashboards/types.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#76 Fix/75/dashboard api
  src/apis/dashboards/index.ts
  src/apis/dashboards/types.ts
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#72 Feat/34/modal
  src/app/globals.css
  src/app/layout.tsx
  src/components/ui/Modal/BaseModal.tsx
  src/components/ui/Modal/DialogContainer.tsx
  src/components/ui/Modal/Modal.tsx
  src/hooks/useAlert.ts
  src/stores/modalStore.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#78 Feat/58 67/users auth api 함수 구현
  src/apis/auth/index.ts
  src/apis/auth/types.ts
  src/apis/users/index.ts
  src/apis/users/types.ts
  src/constants/auth.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#80 Feat/55/invited dashboard component
  src/apis/invitations/mockData.ts
  src/apis/invitations/types.ts
  src/app/(dashboard)/mydashboard/page.tsx
  src/components/invited-dashboard/InvitedDashboardCard.tsx
  src/hooks/useInfiniteInvitations.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#77 Feat/56/profile-edit
  src/components/profile-edit/ProfileEdit.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#82 Feat/54/dashboard list
  src/apis/dashboards/index.ts
  src/apis/dashboards/queries.ts
  src/apis/dashboards/types.ts
  src/app/(dashboard)/dashboard/[id]/page.tsx
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/mydashboard/page.tsx
  src/app/layout.tsx
  src/components/Sidebar/Dot.tsx
  src/components/Sidebar/Sidebar.tsx
  src/components/Sidebar/SidebarItemList.tsx
  src/components/dashboard/CreateDashboard.tsx
  src/components/dashboard/MyDashboard.tsx
  src/components/dashboard/MyDashboardCard.tsx
  src/components/dashboard/MyDashboardList.tsx
  src/components/dashboard/Sidebar.tsx
  src/components/dashboard/SidebarDashboardList.tsx
  src/components/dashboard/SidebarHeader.tsx
  src/components/dashboard/SidebarLogo.tsx
  src/components/pagination/PaginationControls.tsx
  src/components/provider/QueryProvider.tsx
  src/components/ui/Chip/ColorChip.tsx
  src/components/ui/Dot/Dot.tsx
  src/constants/colors.ts
  src/constants/dashboard.ts
  src/utils/helper.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Refactor :recycle:

#83 Feat/29/field components
  src/app/(dashboard)/form/page.tsx
  src/assets/icons/x_white.svg
  src/components/ui/Field/Base.tsx
  src/components/ui/Field/DateInput.tsx
  src/components/ui/Field/ImageUpload.tsx
  src/components/ui/Field/Input.tsx
  src/components/ui/Field/SearchInput.tsx
  src/components/ui/Field/TagInput.tsx
  src/components/ui/Field/Textarea.tsx
  src/components/ui/Field/index.ts
  src/components/ui/Field/types.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#84 Refactor/79/change login management
  next.config.ts
  src/apis/auth/index.ts
  src/apis/users/index.ts
  src/apis/users/types.ts
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/[...endpoint]/route.ts
  src/middleware.ts
  src/utils/network/axiosClientHelper.ts
  src/utils/network/axiosServerHelper.ts
  src/utils/network/errorResponse.ts
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#85 Feat/81/dashboard api modify
  src/apis/dashboards/index.ts
  src/components/dashboard/CreateDashboard.tsx
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#86 Feat/42 43/auth page
  src/apis/auth/index.ts
  src/apis/auth/types.ts
  src/apis/users/index.ts
  src/apis/users/types.ts
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/api/auth/logout/route.ts
  src/components/auth/Checkbox.tsx
  src/components/auth/Field.tsx
  src/components/auth/Header.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/hooks/useAuthStore.tsx
  src/stores/authStore.ts
  src/utils/network/axiosHelper.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#88 Feat/57/password edit
  src/apis/auth/types.ts
  src/app/(after-login)/layout.tsx
  src/app/(after-login)/mypage/page.tsx
  src/app/(before-login)/(auth)/layout.tsx
  src/app/(before-login)/(auth)/login/page.tsx
  src/app/(before-login)/(auth)/signup/page.tsx
  src/app/(before-login)/(landings)/faq/page.tsx
  src/app/(before-login)/(landings)/layout.tsx
  src/app/(before-login)/(landings)/page.tsx
  src/app/(before-login)/(landings)/privacy/page.tsx
  src/components/profile/PasswordEdit.tsx
  src/components/profile/ProfileEdit.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#91 Feat/60/invitations api
  package-lock.json
  package.json
  src/apis/dashboards/index.ts
  src/apis/dashboards/mockData.ts
  src/apis/dashboards/queries.ts
  src/apis/dashboards/types.ts
  src/apis/invitations/index.ts
  src/apis/invitations/mockData.ts
  src/apis/invitations/queries.ts
  src/apis/invitations/types.ts
  src/app/(dashboard)/dashboard/[id]/edit/page.tsx
  src/app/(dashboard)/dashboard/[id]/page.tsx
  src/app/(dashboard)/mydashboard/page.tsx
  src/assets/icons/empty.svg
  src/components/dashboard/CreateDashboard.tsx
  src/components/dashboard/DetailInvited.tsx
  src/components/dashboard/DetailMembers.tsx
  src/components/dashboard/DetailModify.tsx
  src/components/dashboard/InviteDashboard.tsx
  src/components/dashboard/MyDashboardList.tsx
  src/components/dashboard/MyInvitedDashboardList.tsx
  src/components/dashboard/MyInvitedEmptyCard.tsx
  src/components/invited-dashboard/InvitedDashboardCard.tsx
  src/components/ui/Card/Card.tsx
  src/hooks/useDebounce.tsx
  src/hooks/useInfiniteInvitations.ts
  src/utils/errorMessage.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Refactor :recycle:

#96 Refacto/95/dashboard route group
  src/app/(after-login)/dashboard/[id]/edit/page.tsx
  src/app/(after-login)/dashboard/[id]/page.tsx
  src/app/(after-login)/dashboard/page.tsx
  src/app/(after-login)/form/page.tsx
  src/app/(after-login)/mydashboard/page.tsx
  src/app/(dashboard)/layout.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#89 Feat/46/goback link component
  src/components/pagination/Arrow.tsx
  src/components/ui/Link/GoBackLink.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#97 Feat/50/dashboard edit
  src/app/(after-login)/dashboard/[id]/edit/page.tsx
  src/components/dashboard/DetailInvited.tsx
  src/components/dashboard/MyDashboardList.tsx
  src/components/dashboard/MyInvitedDashboardList.tsx
  src/components/pagination/PaginationWithCounter.tsx
  src/components/provider/QueryProvider.tsx
  src/components/ui/Table/Table.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Refactor :recycle:

#98 Feat/64 65 66/columns cards comments api
  package-lock.json
  package.json
  src/apis/cards/index.ts
  src/apis/cards/types.ts
  src/apis/columns/index.ts
  src/apis/columns/types.ts
  src/apis/comments/index.ts
  src/apis/comments/types.ts
  src/utils/isValidDate.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#99 Feat/59/members api
  src/apis/dashboards/types.ts
  src/apis/members/index.ts
  src/apis/members/quries.ts
  src/apis/members/types.ts
  src/app/(after-login)/dashboard/[id]/edit/page.tsx
  src/components/dashboard/DetailDelete.tsx
  src/components/dashboard/DetailInvited.tsx
  src/components/dashboard/DetailMembers.tsx
  src/components/dashboard/DetailModify.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Refactor :recycle:

#100 Ux/94/sidebar
  src/app/(after-login)/layout.tsx
  src/assets/icons/hamburger.svg
  src/assets/images/logo_bi.svg
  src/assets/images/logo_ci.svg
  src/components/dashboard/Sidebar.tsx
  src/components/dashboard/SidebarDashboardList.tsx
  src/components/dashboard/SidebarHeader.tsx
  src/components/dashboard/SidebarLogo.tsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#110 Refactor/103/code review
  src/apis/dashboards/index.ts
  src/apis/dashboards/queries.ts
  src/apis/dashboards/types.ts
  src/apis/invitations/index.ts
  src/apis/invitations/queries.ts
  src/apis/invitations/types.ts
  src/apis/members/index.ts
  src/apis/members/quries.ts
  src/apis/members/types.ts
  src/app/(after-login)/dashboard/[id]/edit/loading.tsx
  src/app/(after-login)/dashboard/[id]/edit/page.tsx
  src/components/dashboard/CreateDashboard.tsx
  src/components/dashboard/DetailDelete.tsx
  src/components/dashboard/DetailInvited.tsx
  src/components/dashboard/DetailMembers.tsx
  src/components/dashboard/DetailModify.tsx
  src/components/dashboard/InviteDashboard.tsx
  src/components/dashboard/MyDashboardList.tsx
  src/components/dashboard/MyInvitedDashboardList.tsx
  src/components/dashboard/SidebarDashboardList.tsx
  src/types/common.ts
  src/utils/network/safeResponse.ts
Labels: Priority: Medium :bookmark:, Type: Bug :bug:, Type: Refactor :recycle:

#112 Fix/92/alert improve
  src/components/dashboard/DetailDelete.tsx
  src/components/ui/Modal/BaseModal.tsx
  src/hooks/useAlert.ts
  src/stores/modalStore.ts
Labels: Priority: Low 🐢, Type: Bug :bug:, Type: Improve UX :arrow_up:

#101 Refactor/90/profile-edit
  src/app/(after-login)/mypage/page.tsx
  src/components/auth/SubmitButton.tsx
  src/components/profile/ProfileEdit.tsx
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#107 Feat/48 49/columns
  src/apis/columns/queries.ts
  src/app/(after-login)/dashboard/[id]/page.tsx
  src/components/columns/AddColumnBtn.tsx
  src/components/columns/ColumnItem.tsx
  src/components/columns/ColumnList.tsx
  src/components/columns/ColumnSettingBtn.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#115 Refactor/109/columns
  src/components/columns/AddColumnBtn.tsx
  src/components/columns/ColumnList.tsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#118 Feat/111/header
  src/apis/members/queries.ts
  src/apis/users/queries.ts
  src/app/(after-login)/layout.tsx
  src/components/dashboard-header/DashboardInfo.tsx
  src/components/dashboard-header/Header.tsx
  src/components/dashboard-header/HeaderButton.tsx
  src/components/dashboard-header/Members.tsx
  src/components/dashboard-header/Profile.tsx
  src/components/dashboard-header/SettingBtn.tsx
  src/components/dashboard-header/Title.tsx
  src/components/dashboard/DetailMembers.tsx
  src/components/ui/Avatar/Avatar.tsx
  src/components/ui/Avatar/StackAvatars.tsx
  src/constants/dashboard.ts
  src/hooks/useMediaQuery.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Refactor :recycle:

#122 Feat/113/use confirm
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/dashboard/DetailDelete.tsx
  src/components/dashboard/DetailInvited.tsx
  src/components/dashboard/DetailMembers.tsx
  src/components/profile/PasswordEdit.tsx
  src/components/ui/Modal/DialogContainer.tsx
  src/hooks/useAlert.ts
  src/hooks/useConfirm.ts
  src/stores/modalStore.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:, Type: Improve UX :arrow_up:

#117 refactor/116/profileedit-schema
  src/apis/users/types.ts
  src/components/profile/ProfileEdit.tsx
  src/constants/profileEdit.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#124 Fix/119/sidebar
  src/components/dashboard/SidebarDashboardList.tsx
Labels: Priority: Low 🐢, Type: Bug :bug:

#126 Feat/40/mypage refactor
  src/apis/users/queries.ts
  src/apis/users/types.ts
  src/app/(after-login)/mypage/loading.tsx
  src/app/(after-login)/mypage/page.tsx
  src/components/dashboard-header/Profile.tsx
  src/components/profile/PasswordEdit.tsx
  src/components/profile/ProfileEdit.tsx
  src/components/ui/Field/ImageUpload.tsx
  src/constants/profileEdit.ts
Labels: Priority: Medium :bookmark:, Type: Refactor :recycle:

#128 Fix/119/sidebar
  src/components/dashboard/SidebarDashboardList.tsx
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#125 UX/120/change-logo
  src/assets/images/logo_bi.svg
  src/assets/images/logo_ci.svg
  src/components/auth/Header.tsx
  src/components/dashboard/SidebarLogo.tsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#131 Feat/108/column item
  src/apis/cards/index.ts
  src/apis/cards/queries.ts
  src/apis/cards/types.ts
  src/apis/columns/types.ts
  src/components/columns/ColumnItem.tsx
  src/components/columns/CreateCard.tsx
  src/components/dashboard/DetailTodo.tsx
  src/components/dashboard/TodoCard.tsx
  src/components/ui/Field/AssignInput.tsx
  src/components/ui/Field/DateInput.tsx
  src/components/ui/Field/ImageUpload.tsx
  src/components/ui/Field/index.ts
  src/utils/convertDateFormat.ts
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#133 Fix/132/middleware-fix
  src/middleware.ts
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#134 Ux/123/datepicker custom
  package-lock.json
  package.json
  src/app/(after-login)/form/page.tsx
  src/assets/css/datepicker.css
  src/assets/icons/circle_arrow_left.svg
  src/assets/icons/circle_arrow_right.svg
  src/components/ui/Field/DateInput.tsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#145 Fix/144/route cache clear
  src/components/auth/LoginForm.tsx
  src/components/dashboard-header/Profile.tsx
  src/middleware.ts
Labels: Priority: High 🔥, Type: Bug :bug:

#143 Docs/136/README.md
  README.md
Labels: Priority: Low 🐢, Type: Doc :memo:

#148 Ux/147/skeleton
  src/app/(after-login)/dashboard/[id]/edit/loading.tsx
  src/app/(after-login)/mypage/loading.tsx
  src/components/ui/Card/Card.tsx
  src/components/ui/Link/GoBackLink.tsx
Labels: Priority: Medium :bookmark:, Type: Improve UX :arrow_up:

#150 Fix/149/Avatar
  src/components/ui/Avatar/Avatar.tsx
Labels: Priority: Medium :bookmark:, Type: Bug :bug:

#151 Refactor/135/todo card
  src/components/columns/ColumnItem.tsx
  src/components/dashboard/DetailTodo.tsx
  src/components/ui/Field/AssignInput.tsx
  src/types/common.ts
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#155 Feat/33/mydashboard complete
  src/apis/dashboards/queries.ts
  src/app/(after-login)/dashboard/[id]/error.tsx
  src/app/(after-login)/dashboard/page.tsx
  src/app/(after-login)/form/page.tsx
  src/components/dashboard/InviteDashboard.tsx
  src/components/dashboard/MyInvitedDashboardList.tsx
Labels: Priority: Medium :bookmark:, Type: Bug :bug:, Type: Refactor :recycle:

#156 Feat/153/comment queries
  src/apis/comments/queries.ts
  src/components/dashboard/CommentSection.tsx
  src/components/dashboard/TodoEditModal.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#160 Feat/152/dnd
  package-lock.json
  package.json
  src/apis/cards/index.ts
  src/apis/cards/queries.ts
  src/components/columns/ColumnItem.tsx
  src/components/columns/ColumnList.tsx
  src/components/dashboard/TodoEditModal.tsx
Labels: Priority: Medium :bookmark:, Type: Bug :bug:, Type: Feature :sparkles:

#162 Refactor/161/card image
  src/components/columns/CreateCard.tsx
  src/components/dashboard/DetailTodo.tsx
  src/components/dashboard/TodoCard.tsx
  src/constants/paths.ts
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#159 Feat/158/comment edit modal
  src/components/dashboard/CommentSection.tsx
  src/components/dashboard/EditCommentModal.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#169 Refactor/163/auth
  src/apis/auth/index.ts
  src/apis/auth/queries.tsx
  src/apis/cards/index.ts
  src/apis/cards/queries.tsx
  src/apis/columns/index.ts
  src/apis/columns/queries.tsx
  src/apis/comments/index.ts
  src/apis/comments/queries.tsx
  src/apis/dashboards/index.ts
  src/apis/dashboards/queries.tsx
  src/apis/invitations/index.ts
  src/apis/invitations/queries.tsx
  src/apis/members/index.ts
  src/apis/members/queries.tsx
  src/apis/users/index.ts
  src/apis/users/queries.ts
  src/apis/users/queries.tsx
  src/components/auth/LoginForm.tsx
  src/components/auth/SignupForm.tsx
  src/components/dashboard-header/Profile.tsx
  src/components/profile/PasswordEdit.tsx
  src/components/profile/ProfileEdit.tsx
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#157 Feat/140/error page
  src/app/error.tsx
  src/app/not-found.tsx
Labels: Priority: Medium :bookmark:, Type: Feature :sparkles:

#171 Refactor/170/readme.md
  README.md
Labels: Priority: Low 🐢, Type: Doc :memo:

#168 Ux/164/longtext
  src/components/dashboard/DetailTodo.tsx
  src/components/dashboard/TodoCard.tsx
  src/components/ui/Dropdown/Dropdown.tsx
Labels: Priority: Low 🐢, Type: Improve UX :arrow_up:

#167 Refactor/166/comment section
  src/components/dashboard/CommentSection.tsx
  src/components/dashboard/EditCommentModal.tsx
Labels: Priority: Low 🐢, Type: Refactor :recycle:

#177 Fix/175/skeleton ui gap 추가
  src/app/(after-login)/dashboard/[id]/edit/loading.tsx
  src/app/(after-login)/mypage/loading.tsx
Labels: Priority: High 🔥, Type: Bug :bug:

#176 Fix/174/dashboard, invitation, members 리스트 패칭 쿼리함수에 쿼리키 수정
  src/apis/dashboards/queries.ts
  src/apis/invitations/queries.ts
  src/apis/members/queries.ts
Labels: Priority: High 🔥, Type: Bug :bug:

#181 Fix/179/todo card fix
  src/components/todo/TodoCard.tsx
Labels: Priority: Low 🐢, Type: Bug :bug:, Type: Improve UX :arrow_up:

#183 Fix/182/column title elipsis
  src/components/columns/ColumnItem.tsx
  src/components/columns/ColumnList.tsx
  src/components/columns/ColumnSettingBtn.tsx
  src/components/todo/CommentSection.tsx
  src/components/todo/EditCommentModal.tsx
  src/components/todo/TodoCard.tsx
  src/components/ui/Button/DashboardButton.tsx
Labels: Priority: High 🔥, Type: Bug :bug:
